PROYECT_ORIGIN_PATH: /home/benat/Personal/01 - BIOLAN Proyects/01 - Biolan global/biolan
#PROYECT_ORIGIN_PATH: ./__Result
SCOPE: Biolanglobal
USER_TYPE: Internal
DJANGO_MODEL_NAME: DummyCell
DJANGO_MODEL_EXTENDS: BaseModel
DJANGO_MODEL_PARAMS:
   code: models.CharField(max_length=10, unique=True)